
name: CI Build

on: [push, pull_request]

jobs:   
  build-modern:
    name: UAE4ALL for MiyooCFW (uClibc)
    runs-on: ubuntu-22.04
    container:
      image: miyoocfw/toolchain-shared-uclibc
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make -j$(nproc)
    - uses: actions/upload-artifact@v4
      with:
        name: UAE4ALL binary
        path: uae4all
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
